### ISSUE TITLE
vlan association issue

### ISSUE THREAD

**Issue by mattpascoe** [opennetadmin/ona#104]
When adding a vlan to a subnet when the vlan utilzes vlan number that is duplicated within another campus via the GUI, you get an error that it can not find the vlan.

However if you add it using DCM and specify campus and vlan it does seem to work.  

May be related to issue #99

**Comment by vigodeltoro** [comment]
Hi,

I have the same issue.. 
We need this for our datacenter and for continous deployment..

I assume that only the vlan used as key and the amount of subnets which is returned from DB is more then one in the array.. We tried to analyse the bug .. 
It looked like that the Value for the campus wouldn't be returned if the vlan number and name in both campuse are similar..

Is it possible to fix this issue ? Or do you have a hint for me where i have to look and change the code ?

I'm on the master release v13.03.01

Thanks a lot

regards

Chris

**Comment by dmgeurts** [comment]
Any chance this could be looked into. It's a bit odd that VLAN-ids can't be reused across campuses.
