### ISSUE TITLE
Best way to interoperate with PowerDNS

### ISSUE THREAD

**Issue by b4** [opennetadmin/ona#108]
Hello,

We're running MySQL-backed PowerDNS for authoritative DNS...what'd be the best way to allow the two to coexist happily with PowerDNS being aware of ONA's DNS database?

**Comment by mattpascoe** [comment]
The simple statement I have at this point is I don't know.  I personally have not used PowerDNS so I can't speak directly to that. There have been queries in the past about this but I have not heard exactly how those people solved the issue.  As I understand it, PowerDNS has a BIND compatibility mode which I would hope would allow it to just read in the configurations the ONA bind module produces.  This is likely non optimal.  

As with the [Bind-DLZ](https://github.com/opennetadmin/ona/wiki/Bind-DLZ) methods I suspect it is possible one could write up some direct SQL interactions that might work.. This would be more complex to test out.  

Beyond that I would suspect that some other module or function could be build to help tie the two together.  

At this point I would have to leave those solutions up to others to work out.  I'd certainly join in the conversation and design of it but can't commit to implementation.  Maybe others will weigh in on any solutions they have.
