### ISSUE TITLE
Suggested way of backing up ONA?

### ISSUE THREAD

**Issue by ChinookTx** [opennetadmin/ona#114]
This is not a problem per say, but I'm wondering if there is a suggested way of backing up ONA for easy recovery/restore.  

I'm contemplating upgrading hardware and don't quite remember everything I had to do to make it work on my current platform.

Would a mysql dump of the DB and tar of /opt/ona be enough?  Am I forgetting anything?

**Comment by mattpascoe** [comment]
You pretty much have the idea.  

I went ahead and put a [wiki page](https://github.com/opennetadmin/ona/wiki/Backups) on backups to give some other ideas.

I also typically just do a git clone of the ona repo into /opt/ona.. then this way if I make any changes to anything I can do a git diff and see exactly what I changed.  This is just an alternative thought.
