### ISSUE TITLE
Assign DNS-Server to domain failed

### ISSUE THREAD

**Issue by udoL** [opennetadmin/ona#119]
Hi,
just installed the actual ona version 17.12.22 and tried to assign an domain to an server-ip.

I got the error:
Jan 1 16:55:37 is admin@192.168.100.25: [DEFAULT] ERROR => domain_server_add() SQL Query failed:ERROR => SQL INSERT failed: Field 'type' doesn't have a default value

The domain looks normal:
domain.de
Domain SOA Parameters 
Primary Master  	is.domain.de 
Refresh  	86400 
Retry  	3600 
Expiry  	3600 
Minimum  	3600 
Default TTL  	86400

Any idea?

Best regards

Udo

**Comment by mattpascoe** [comment]
Ok I believe I have this and a few other things fixed up.  If you could test again using the 'develop' branch and let me know if that fixes your issues. 

You will want to run the installer again.  you can do this by adding '?runinstaller=y' to your URL.

Thanks much.

**Comment by mattpascoe** [comment]
devlop branch is now merged to master.. please get the latest release.

**Comment by udoL** [comment]
Hi,
sorry for late reply.

Thanks!! work like a charme now.
