### ISSUE TITLE
upgrading 13.03.01 to 17.12.22 with remote mysql server

### ISSUE THREAD

**Issue by niesenjo** [opennetadmin/ona#121]
After successfully grabbing the version information from the db using the local settings username and password for the remote db, the upgrade process errors that access is denied for the user "using password: NO". Attaching an image of this result:

![onaupgrade](https://user-images.githubusercontent.com/35077567/34536381-ec4bf2a4-f092-11e7-8f3a-157e8855312d.jpg)

Testing password changes, it appears that by changing the settings to a non-working password, the initial  evaluation of the db returns with access is denied for the user "using password: YES" as compared to this message saying it is not using password. This doesn't return the version information when doing tests.

**Comment by mattpascoe** [comment]
I just released another new version this morning.  I believe it will fix these issues.  Please give v18.1.1 a try and see if it works for you.

Not that it really should make a difference but you can try `php /opt/ona/install/installcli.php` and see if things work that way.

**Comment by niesenjo** [comment]
Using v18.1.1 resolved this issue. Thanks!
