### ISSUE TITLE
Import VLAN information from file csv or other format

### ISSUE THREAD

**Issue by romano80** [opennetadmin/ona#131]
Hi all,
I'm a new user of openNetAdmin I just finished some minutes ago the installation and I would like to know if there is a way to import vlan information and host from a csv file for example

Sorry for my bad English

**Comment by Gankarloo** [comment]
For this you need dcm
It's a plugin to do exactly what you wish.

https://github.com/opennetadmin/dcm

**Comment by romano80** [comment]
Hi Installed the plugin but I don't find infomation about file format or command ? can you help me?
thanks Romano

**Comment by Gankarloo** [comment]
Start with reading the Readme.md in dcm repo. All you need should be there.
