### ISSUE TITLE
More neutral user avatars?

### ISSUE THREAD

**Issue by chuhn** [opennetadmin/ona#135]
The current user info dialog avatar icon is a Strong Bad image that links to Homestar Runner web page: https://github.com/opennetadmin/ona/blob/53c03bcd8eccd7216ec9cc8ab8c70a44d58fa08d/www/winc/app_user_info.inc.php#L51

I appreciate that but I think it might be confusing to some users.
It would be nice to turn that into a configuration setting.

Individual avatars would be even nicer.

**Comment by mattpascoe** [comment]
Ahh yes, the Strong Bad image.  A silly addition added almost 15 years ago.  My goodness its been that long!?  Here is my take on it at this point.

While users are necessary for the system, the management of non relevant metadata such as avatars etc are probably not worth the time.  Especially when used with external auth systems such as ldap. 

If anything, I would probably just remove the silly Strong Bad link, as much fun as it was.
