### ISSUE TITLE
PHP 7.2 migration from 7.0 with LDAP authentification keeps failing

### ISSUE THREAD

**Issue by MangeChats** [opennetadmin/ona#139]
From what I found it looks like it has to do with a PHP Deprecated warning:
Methods with the same name as their class will not be constructors in a future version of PHP

load_auth_class() returns that the class auth_ldap exists but it fails to initialize
so that the next call to $auth->checkPass() fails and the password check always fails

This prevents using ONA on a 18.04 Ubuntu server for example

I'm affraid I won't find the solution myself

**Comment by mattpascoe** [comment]
I am closing this issue as I believe it to now be fixed in the development branch.. I'm currently doing testing on ubuntu 19.10 and have resolved these sorts of issues.
