### ISSUE TITLE
Initial configuration issue

### ISSUE THREAD

**Issue by nrietsch** [opennetadmin/ona#141]
Setup:
Ubuntu 16.04 LTS fully patched
ONA v18.1.1

I kept having a problem when running the initial configuration using the browser.
When submitting the form, I would just get a blank screen and nothing was created.

When running the cli version, I noticed that the PHP XML test failed.

Once I installed the PHP XML module (and restarted Apache), the GUI install would work.

In other words, it may be a good idea to add the PHP XML test in the GUI mode...

**Comment by nrietsch** [comment]
Should I close the issue?

**Comment by mattpascoe** [comment]
No we can leave it open.. it will serve as a reminder until I ACTUALLY update the code.  I'll close it when I do.  Thanks again!

**Comment by nrietsch** [comment]
my pleasure...
