### ISSUE TITLE
How to add DNS/DHCP?

### ISSUE THREAD

**Issue by TareqK** [opennetadmin/ona#146]
Ive been scouring the wiki, forums, manuals, for the last 2 days, but i still have no idea how to add dns/dhcp servers and how to have ONA manage them.

**Comment by mattpascoe** [comment]
Sorry for the late reply.

Once you have ONA itself installed, you then need to install the appropriate plugin. So for example the DHCP plugin https://github.com/opennetadmin/build_isc_dhcp.  That page explains how to install the plugin and set it up.  

Other plugins of course are listed here: https://github.com/opennetadmin/ona/wiki/plugins.  Each plugin should have information explaining how to use it.

Please let me know if that information is not what you needed and I can give you more details.
