### ISSUE TITLE
Fresh install fails (ubuntu 19.10)

### ISSUE THREAD

**Issue by dmgeurts** [opennetadmin/ona#148]
Fresh install on a Raspberry pi (natively supported since 19.10).

- Connected to 'localhost' as 'root'.
- Dropped existing instance of 'ona_default'.
- Created new database 'ona_default'.
- Selected existing DB: 'ona_default'.
- There was an error processing tables.
-- You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups ( id INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT, ' at line 1
-  There was a fatal error. Install may be incomplete. Fix the issue and try again.

PHP version 7.3
MySQL version 8.0.18 (MariaDB)

**Comment by dmgeurts** [comment]
I can manually create the groups table using the code from /opt/ona/install/ona-table.sql tp create table 'groups'.

**Comment by dmgeurts** [comment]
Using the CLI installer yields the same result. But doesn't show any errors.

**Comment by dmgeurts** [comment]
Using the dev branch and CLI I get the same error as when using the webinstall:
```
There was an error processing tables.
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server 
version for the right syntax to use near 'groups (
id                       INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT,
' at line 1
There was a fatal error. Install may be incomplete. Fix the issue and try again

```

**Comment by dmgeurts** [comment]
Found the issue. the conversion from xml file to sql doesn't wrap table names in back-ticks (`). The table called groups must be wrapped in these for the sql table creation to work.

**Comment by dmgeurts** [comment]
Wrapping the groups table name in backticks in the xml schema file resolves that issue. Next:

```
ERROR => There was an error creating DB user: You have an error in your SQL syntax; check the manual that co
rresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'xxxxxxxxxx'' at line 1
```

**Comment by mattpascoe** [comment]
I have an idea of why its not working.. mysql 8+ has made some changes to how the user is created.  I need to test a few things and see what I can come up with.  It should just be an update to the syntax of the user create.

**Comment by cj0nes** [comment]
Are there any updates to this? Or at least a workaround? I'm hitting the same issue with the DB user creation.

**Comment by mattpascoe** [comment]
@cj0nes there are some workarounds we might try but first, have you tried the development branch?  It had some updates that should have fixed the issue.  Please confirm if it is, or is not working for you.  Thanks!
