### ISSUE TITLE
Custom nmap_scan type

### ISSUE THREAD

**Issue by dmgeurts** [opennetadmin/ona#152]
More a question about how this custom type is linked to a subnet. Enabling the nmap plugin, I can scan and see the results, but I'm unable to find how to set Y or N on a prefix.

**Comment by mattpascoe** [comment]
- Navigate to the subnet in question
- Select Menu -> Workspace -> Add Custom Attribute
- Select "nmap scan" type and enter either Y or N for a value.

The custom attributes are a bit hidden.. once, you add one they show up on the main display.

**Comment by dmgeurts** [comment]
Thank you, all sorted.
