### ISSUE TITLE
NMAP_SCAN_CRON throwing error

### ISSUE THREAD

**Issue by mlfierro72** [opennetadmin/ona#155]
I just configured the plugin and everything as far as I can see looks correct, and my subnets however when I run nmap_scan_cron -l, instead returning the list of subnets, I get:

select CONCAT(INET_NTOA(ip_addr),'/',32-log2((4294967296-ip_mask))) net
from subnets
where id in (
        SELECT table_id_ref
        FROM custom_attributes
        WHERE table_name_ref = 'subnets'
        AND value = 'Y'
        AND custom_attribute_type_id = (
                SELECT id
                FROM custom_attribute_types
                WHERE name LIKE 'nmap_scan' )
  )
order by ip_addr'<br>
3
ERROR => SQL query failed:

and when I run nmap_scan_cron -a, I get:

INFO => Running NMAP ping only scan on Input...
Failed to resolve "Input".
WARNING: No targets were specified, so 0 hosts scanned.
INFO => Running NMAP ping only scan on array...
Failed to resolve "array".

**Comment by mattpascoe** [comment]
hmm interesting.. I'll see if I can re-create the problem.. can you provide more information about your environment?  Versions of OS, php, database etc. 

If you have not, try setting the custom attribute 'nmap_scan' set to 'Y' on the subnets you wish to scan.

**Comment by mlfierro72** [comment]
Ubuntu 18.04.4 LTS
MySQL Ver 14.14 Distrib 5.7.29
PHP 7.2.24
Apache 2.4.29

I’ve got the custom attribute nmap_scan set to Y on all the subnets.

Thanks!

**Comment by mlfierro72** [comment]
I've run the script manually and this is the output where $SQLFILE is /opt/ona/www/plugins/ona_nmap_scans/sql/nmap_subnets.sql :

/opt/ona/bin$ sudo ./dcm.pl -r ona_sql header=no sql=$SQLFILE
Input array has 1 params, does not match query: '-- Lists all subnets with CIDR mask, use for nmap_ona_audit.php
--
-- LONG_DESC:
--      This query returns all subnets from the database in
--      network-ip/cidr notation.  It will NOT return subnets that
--      have the &quot;nmap_scan&quot; custom attribute set to &quot;N&quot;.
--
--      The intent is that this list will be used as a seed for
--      doing nmap scans of all subnets in the database.
--      If you wish to find ONLY subnets that are flagged as &quot;Y&quot;
--      then use the nmap_subnets_only_yes.sql file instead.
--

select CONCAT(INET_NTOA(ip_addr),'/',32-log2((4294967296-ip_mask))) net
from subnets
where id not in (
        SELECT table_id_ref
        FROM custom_attributes
        WHERE table_name_ref = 'subnets'
        AND value = 'N'
        AND custom_attribute_type_id = (
                SELECT id
                FROM custom_attribute_types
                WHERE name LIKE 'nmap_scan' )
  )
order by ip_addr

'<br>
3
ERROR => SQL query failed:

**Comment by mlfierro72** [comment]
[I've run this manually where $SQLFILE is /opt/ona/www/plugins/ona_nmap_scans/sql/nmap_subnets.sql

sudo ./dcm.pl -r ona_sql header=no sql=$SQLFILE
Input array has 1 params, does not match query: '-- Lists all subnets with CIDR mask, use for nmap_ona_audit.php
--
-- LONG_DESC:
--      This query returns all subnets from the database in
--      network-ip/cidr notation.  It will NOT return subnets that
--      have the &quot;nmap_scan&quot; custom attribute set to &quot;N&quot;.
--
--      The intent is that this list will be used as a seed for
--      doing nmap scans of all subnets in the database.
--      If you wish to find ONLY subnets that are flagged as &quot;Y&quot;
--      then use the nmap_subnets_only_yes.sql file instead.
--

select CONCAT(INET_NTOA(ip_addr),'/',32-log2((4294967296-ip_mask))) net
from subnets
where id not in (
        SELECT table_id_ref
        FROM custom_attributes
        WHERE table_name_ref = 'subnets'
        AND value = 'N'
        AND custom_attribute_type_id = (
                SELECT id
                FROM custom_attribute_types
                WHERE name LIKE 'nmap_scan' )
  )
order by ip_addr

'<br>
3
ERROR => SQL query failed:](url)
________________________________

**Comment by mike-kll** [comment]
Thats it, it works now.

Thanks a lot Gankarloo!!!

**Comment by mlfierro72** [comment]
This fixed it!  Thank you so much!

**Comment by mlfierro72** [comment]
> Try this #126

This fixed it!  Thank you!
