### ISSUE TITLE
mysql 8 and table "groups"

### ISSUE THREAD

**Issue by norge-ice** [opennetadmin/ona#156]
is impossible to create a table with name "groups" in mysql 8, during installation, because is a Reserved Words( https://dev.mysql.com/doc/refman/8.0/en/keywords.html )

**Comment by mattpascoe** [comment]
I am aware of this. I have started work to make the adjustments for this.  Please try the development branch as it should address this issue.  Thank you.

**Comment by mattpascoe** [comment]
closing as a dupe of #150
