### ISSUE TITLE
PHP Fatal error:  Cannot unset $this

### ISSUE THREAD

**Issue by nkovacne** [opennetadmin/ona#157]
Just cloned ONA from Git, followed instructions [here](https://github.com/opennetadmin/ona/wiki/Install) and when lauching the web installer, I get this error in apache logs:

`[Thu Apr 16 00:31:23.133429 2020] [php7:error] [pid 19320] [client X:51510] PHP Fatal error:  Cannot unset $this in /var/www/ona/include/adodb5/adodb-xmlschema03.inc.php on line 178`

Is this a known issue, or is there any workaround for this?

Environment is Ubuntu 18.04 with apache 2.4.29 and PHP 7.2.

**Comment by mattpascoe** [comment]
If you have done a git clone you are likely on the master branch.  Try doing a `git checkout develop` while in your /opt/ona directory.. This will switch you over to the development branch which has several fixes for newer PHP and mysql environments. 

See if that addresses your problem.  I'm still working to fix some outlying things in that branch before I merge it back to master.  Your testing here would be much appreciated.  Thanks!

**Comment by nkovacne** [comment]
That did the trick! Thanks so much for the great work.
