### ISSUE TITLE
Deprecated: Methods on PHP 7

### ISSUE THREAD

**Issue by norge-ice** [opennetadmin/ona#158]
I've installed ONA on rhel 8 with PHP 7 and at first access I received some errors like this:

"Error: the XML response that was returned from the server is invalid. Received:
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; xajax has a deprecated constructor in /opt/ona/www/include/xajax_0.2.4/xajax.inc.php on line 75"

I modified this files substitution the function with the same name of the class:

/opt/ona/www/include/xajax_0.2.4/xajax.inc.php  substitute "function xajax" with "public function __construct" in line 172
/opt/ona/www/include/xajax_0.2.4/xajaxResponse.inc.php  substitute "function xajaxResponse" with "public function __construct" in line 102
/opt/ona/www/include/auth/local.class.php  substitute "function auth_local" with "public function __construct" in line 24
/opt/ona/www/include/auth/ldap.class.php  substitute "function auth_ldap" with "public function __construct" in line 19

I hope they are the only functions to be changed.

**Comment by mattpascoe** [comment]
These issues should now be resolved in the latest version v19.0.0
