### ISSUE TITLE
rndc.key

### ISSUE THREAD

**Issue by dmgeurts** [opennetadmin/ona#160]
I see that extra DNS records can be included from a web server. But is there a way to include "allow-update { key rndc-key; };" for zones to allow ddns?

For example:

```
zone "test.local" in {
  type master;
  file "/opt/ona/etc/bind/zone_data/named-test.local";
  allow-update { key rndc-key; };
};
```

Thanks,

**Comment by mattpascoe** [comment]
Sorry, somehow I totally missed this issue when you opened it.  

At this time there is not a provision for adding extra information into the zone level configuration.  However, if you wanted that allow-update setting on ALL of your zones, it would be a pretty simple add to the zone configuration script to just always print that line. 

You could add it [on this line](https://github.com/opennetadmin/build_bind/blob/master/build_bind.inc.php#L235)
