### ISSUE TITLE
DNS Server Entries Error with MariaDB >= 10.2

### ISSUE THREAD

**Issue by raabf** [opennetadmin/ona#161]
Lets assume you are running your ONA database on a MariaDB server >= 10.2 and access a “DNS server” entry, then the following does happen: 

![2020-09-13 21_01_22-OpenNetAdmin __ 0wn Your Network - Vivaldi](https://user-images.githubusercontent.com/4788201/93254754-23bf0680-f799-11ea-83ad-b089b26e1349.png)

After some seconds the page freezes for quite a long time (can be over a minute). Actually ONA freezes completely, if you access the same ONA on another webbrowser, loading of the page is also blocked until the freeze is over. After the freeze the error in the picture is shown, and I am forced to log-in again. Note that the `Assigned domains` list which is seen in the background of the picture does not load and keeps empty, although the the preview of the bind9 named zone file below seems to be complete. Also the “trace”  bar in ONA of your visited entries is erased. This can also happen with DNS Server related operations like viewing the server 'a.ns.li.raab.link` in the example in the picture, or any modifications affecting the DNS Servers.
This error is not 100% guaranteed to arise, but very likely and happens most of the time, I would describe it unusable in this state  (especially modifying the DNS Server is near to impossible).

I have absolutely no problems with MariaDB 10.1, I also tested MySQL 5.7 and the error also arises there.
In detail, I have tested the following MariaDB versions, which does have the error:
MariaDB 10.2.33, 10.3.23, 10.3.24, 10.5.5 and MySQL 5.7.31

And the  following versions still work fine:
MariaDB 10.1.44, and 10.1.46

I do run ONA on an own MariaDB 10.1 container, so I am currently fine, but one additional problem is that MariaDB 10.1 is end of life (EOL) in a month (mid October 2020). Sadly I do not have any further insight about the cause of the error.

**Comment by robfantini** [comment]
at our ona system which runs on debian buster, this works for us:

apt show mariadb-server-10.3
Package: mariadb-server-10.3
Version: 1:10.3.23-0+deb10u1

**Comment by mattpascoe** [comment]
should now be fixed with v19.0.0
