### ISSUE TITLE
Valid IPv6 subnet masks not allowed

### ISSUE THREAD

**Issue by gjlampard** [opennetadmin/ona#166]
I was trying out the demo looking at IPv6 functionality and created a couple of IPv6 subnets.
I was surprised to find the allowed prefix sizes are constrained to a limited set of values e.g.  /48, /64, /65, /66
Some prefix lengths are more common than others, but any value from /0 to /127 is allowed.
There's maybe an argument that nobody needs anything shorter than /20, but there are legitimate uses for all prefix lengths longer than that, all the way out to /127.

Is this restriction just for the demo, or does it apply to the code?
In either case, can the restriction be removed, and any value accepted?
They don't have to all appear in the drop-down, but as a minimum /56 should be in the drop-down list.

**Comment by mattpascoe** [comment]
So these are just suggestions and you should be able to provide any /XX value you wish to assign the subnet to.  I certainly could add more to the suggestion list but there are diminishing returns.  I guess the intent was really "common" prefixes, although that is a debatable list as well.  

Again you are able to type in any value you desire here. I usually find myself typing it in as opposed to selecting it with the mouse from the suggested list.  This is one reason I didn't add many to the suggestions.  I'd be fine adding some to the list if there is a strong wish to do so.

**Comment by gjlampard** [comment]
Thanks Matt.  Yep, works fine.   My mistake.  I thought I'd tried to type in the value, but I must have just stopped when I saw the "No suggestions" text pop up.  
I agree that it's not practical to pick out the most common IPv6 prefix lengths.   
If the pop-up text said "No suggestions, please type required value" it would have saved me bothering you, but I can't really call it a bug, so I'm closing this issue.
