### ISSUE TITLE
dcm.pl build_dhcpd_conf  - question on changing output

### ISSUE THREAD

**Issue by robfantini** [opennetadmin/ona#190]
Hello Matt

currently reservations are out put like this:

host 10.1.3.9 {  # edi.example.com
    fixed-address 10.1.3.9;
    hardware ethernet DE:72:3C:EB:11:72;
}

which file do I need to edit to get this:

host edi.example.com {
    fixed-address 10.1.3.9;
    hardware ethernet DE:72:3C:EB:11:72;
}

This change will help in our migration to kea dhcp

**Comment by mattpascoe** [comment]
@robfantini You'll want to edit this file [here](https://github.com/opennetadmin/build_isc_dhcp/blob/982136268e9176d1362c54fb68bd68ac3b903155/build_isc_dhcp.inc.php#L508)

This would likely be located in /opt/ona/www/local/plugins/build_isc_dhcp on your system.
