### ISSUE TITLE
Add does not work at Device Model and Device Type

### ISSUE THREAD

**Issue by robfantini** [opennetadmin/ona#191]
using v19.0.1  , when Add is clicked the screen to Add does not pop up.

**Comment by heppel** [comment]
I can confirm this for ONA 19.0.1 running on Debian 12 with PHP 8.4.

PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /opt/ona/www/winc/app_device_model_edit.inc.php:60\nStack trace:\n#0 /opt/ona/www/include/xajax_webwin/webwin.inc.php(173): ws_editor()\n#1 /opt/ona/www/include/xajax/xajax_core/plugin_layer/support/xajaxUserFunction.inc.php(237): window_submit()\n#2 /opt/ona/www/include/xajax/xajax_core/plugin_layer/xajaxFunctionPlugin.inc.php(228): xajaxUserFunction->call()\n#3 /opt/ona/www/include/xajax/xajax_core/xajaxPluginManager.inc.php(277): xajaxFunctionPlugin->processRequest()\n#4 /opt/ona/www/include/xajax/xajax_core/xajax.inc.php(603): xajaxPluginManager->processRequest()\n#5 /opt/ona/www/include/xajax_setup.inc.php(49): xajax->processRequest()\n#6 /opt/ona/www/index.php(50): require_once('...')\n#7 {main}\n  thrown in /opt/ona/www/winc/app_device_model_edit.inc.php on line 60, referer: http://ona.intern.heinopeters.de/ona/

**Comment by robfantini** [comment]
Hi Matt
 If you would like to have ssh access to a Debian 12 system with the following php version let me know.

# php -v
PHP 8.2.20 (cli) (built: Jun 17 2024 13:33:14) (NTS)

**Comment by mattpascoe** [comment]
@robfantini I dont think I'll need access. I was able to recreate the issue locally and my commit fixes the issue for me.  I just need to get it merged and released. I hope to have that done soon. Thanks!
