### ISSUE TITLE
BUG: dcp.pl -r  subnet_add

### ISSUE THREAD

**Issue by dongreer** [opennetadmin/ona#49]
After creating a vlan "X" on campus "Foo" with subnet "10.1.2.0/24", then adding vlan "X" on campus "Bar" with subnet "10.2.2.0/24" failes with "ERROR => The vlan/campus pair specified is invalid!"

I can do exactly the same creation through the GUI.  I've not dug into the code, but I strongly suspect that dcm.php or something is doing a check to make sure that the VLAN is not a duplicate, rather than the VLAN/Campus is not a duplicate.  I'll go digging for this and if I find something, I'll update where it is.

**Comment by nicsaravanan** [comment]
Hi, 

We are also getting the same error, we tried to modify the functions_db.in.php as described above but not working

# ./dcm.pl -r subnet_add name=TESTSSH1 ip=192.168.103.16 netmask=255.255.255.248 type=VLAN campus=TEST-VLAN-CAMPUS vlan=3002

ERROR => The vlan/campus pair specified is invalid!
