### ISSUE TITLE
VMWare plugin does not work with 5.x

### ISSUE THREAD

**Issue by rdorman** [opennetadmin/ona#52]
When pointing the vmware stats plugin at a 5.x vcenter I recieve the following (truncated) error

" PHP Fatal error:  Uncaught SoapFault exception: [ServerFaultCode] Attribute name xsi:type uses an undefined namespace prefix xsi\n\nwhile parsing MoRef for ManagedObject of

**Comment by SyBernot** [comment]
I just hit this as well. Seems like the XML may be different. Is there an easy fix?

**Comment by mattpascoe** [comment]
I think I have this fixed.. I just checked in a vmware5 branch on the plugin opennetadmin/vmware_stats repo.  Give that branch a try and see if it is functional for you.  I'm currently using that on our vmware5 systems.  its 'mostly' working for me :)

**Comment by SyBernot** [comment]
I can confirm this mostly works on VCenter 5.5

Broken stuff: 
console link is broken (but even from the vmware web client that is hit and miss for me) 
cluster doesn't populate
IPs doesn't populate sometimes (I think it's just multi-homed vms )  

All in all not a big deal for me.

**Comment by mattpascoe** [comment]
closing ticket as it is working.. there are a few items as mentioned that could be improved.. new tickets on this should be opened on the other repo.
