### ISSUE TITLE
Unable to add a subnet using dcm.pl

### ISSUE THREAD

**Issue by nicsaravanan** [opennetadmin/ona#97]
Hi, 

we want to add a subnet using dcm.pl , when we try we are getting the following error

 #/dcm.pl -r subnet_add name=newsub ip=192.168.104.0 netmask=255.255.255.0 type=VLAN vlan=OC-1,100 campus=OC

ERROR => The vlan/campus pair specified is invalid!

the VLAN 100 is already part of campus "OC"

**Comment by mattpascoe** [comment]
just checked in an update that should fix this.  the vlan lookup function was not actually dealing with vlan numbers properly.  If you pull from master you can get that update.
